package com.digdes.school.operation;

public enum LexemeType {
    INSERT_QUERY_TYPE,
    SELECT_QUERY_TYPE,
    UPDATE_QUERY_TYPE,
    DELETE_QUERY_TYPE,
    LOGIC_OPERATION_TYPE,
    COMMON_OPERATION_TYPE,
    COMMA_TYPE,
    OPENING_PARENTHESIS_TYPE,
    CLOSING_PARENTHESIS_TYPE,
    STRING_TYPE,
    BOOLEAN_TYPE,
    LONG_TYPE,
    DOUBLE_TYPE,
    NULL_TYPE
}
